[1000]
path = "battle"

[1000.1]
path = "battle_data_release"

3.path = "equipment.xlc"

5.path = "sundries.xlc"
6.path = "classes.xlc"
7.path = "class_text.xlc"
8.path = "abilities.xlc"
9.path = "map_parties.xlc" # not sure if completely accurate

15.path = "racial_templates.xlc"

17.path = "skills.xlc"

20.path = "random_character_names.xlc"

27.path = "battle_text.xlc"
28.path = "factions.xlc"

37.path = "map_spawn_coordinates.xlc"
38.path = "battle_death_messages.xlc"
39.path = "battle_skill_messages.xlc"
40.path = "battle_notification_messages.xlc"

42.path = "spell_sets.xlc"

[1000.1.0]
path = "unit_animations"

[1000.1.1]
path = "weapon_animations"

[1000.1.2]
path = "misc_graphics"

1.path = "cursor.spr"

3.path = "loot_bag.spr"
4.path = "status_icons.spr"
5.path = "tile_selection_border.spr"

8.path = "unit_palettes.spr"
