[20]
path = "object/actor"

1.path = "Adult_f"
2.path = "Adult_m"
3.path = "Aged_f"
4.path = "Aged_m"
5.path = "Andoras"
6.path = "Archer_f"
7.path = "Archer_m"
8.path = "Athelstan"
9.path = "Balbatos"
10.path = "Balzepho"
11.path = "Balzepho_overcoat"
12.path = "Barnas"
13.path = "BeastTamer_f"
14.path = "BeastTamer_m"
15.path = "Berserker_f"
16.path = "Berserker_m"
17.path = "boy_a"
18.path = "boy_b"
19.path = "boy_c"
20.path = "Branta"
21.path = "Canopus"
22.path = "Cleric_f"
23.path = "Cleric_m"
24.path = "Cockatrice"
25.path = "Cressida"
26.path = "Cyclops"
27.path = "Delilah"
28.path = "Deneb"
29.path = "Denim"
30.path = "DenimLord"
31.path = "DivineKnight_f"
32.path = "DivineKnight_m"
33.path = "Dknight"
34.path = "Dorgalua"
35.path = "DorgaluaXL"
36.path = "Dra_Ark"
37.path = "Dra_Cloud"
38.path = "Dra_Dark"
39.path = "Dra_Earth"
40.path = "Dra_Flame"
41.path = "Dra_Flood"
42.path = "Dra_Frost"
43.path = "Dra_Thunder"
44.path = "Dragoon_f"
45.path = "Dragoon_m"
46.path = "Fairy"
47.path = "Farfadets"
48.path = "Ganb"
49.path = "Ghost"
50.path = "Gilbert"
51.path = "girl"
52.path = "Gol_Clay"
53.path = "Gol_Iron"
54.path = "Gol_Stone"
55.path = "Gol_Vulder"
56.path = "Gremlin"
57.path = "Gryphon"
58.path = "Guildus"
59.path = "Gunner_f"
60.path = "Gunner_m"
61.path = "Hawkman"
62.path = "Hobyrim"
63.path = "Hydra"
64.path = "Kachua"
65.path = "kachuadark"
66.path = "kachuaprincess"
67.path = "klaire"
68.path = "Knight_f"
69.path = "Knight_m"
70.path = "Lamia"
71.path = "LansHami"
72.path = "LansTar"
73.path = "LansTar_overcoat"
74.path = "Leonard"
75.path = "Lich_f"
76.path = "Lich_m"
77.path = "Lindl"
78.path = "Lizardman"
79.path = "Luxian"
80.path = "mannaflora"
81.path = "Martym"
82.path = "middle_f"
83.path = "middle_m"
84.path = "Mildain"
85.path = "Modigliani"
86.path = "mreuva"
87.path = "Necromancer_f"
88.path = "Necromancer_m"
89.path = "Ninja_f"
90.path = "Ninja_m"
91.path = "Nybbas"
92.path = "Octopus"
93.path = "Olivia"
94.path = "Orc"
95.path = "Orias"
96.path = "Oz"
97.path = "Ozma"
98.path = "Prancet"
99.path = "Pumpkin"
100.path = "Ravness"
101.path = "Rodrick"
102.path = "rodrickchild"
103.path = "Ronwey"
104.path = "Rouge_f"
105.path = "Rouge_m"
106.path = "Selye"
107.path = "Shelley"
108.path = "Sisteena"
109.path = "Skeleton"
110.path = "Sorcerer_f"
111.path = "Sorcerer_m"
112.path = "Swordmaster_f"
113.path = "Swordmaster_m"
114.path = "TerrorKnight_f"
115.path = "TerrorKnight_m"
116.path = "Valkyrie_f"
117.path = "Valkyrie_m"
118.path = "vernotta"
119.path = "Vice"
120.path = "vicedaddy"
121.path = "Volac"
122.path = "Volac_overcoat"
123.path = "Warren"
124.path = "Warrior_f"
125.path = "Warrior_m"
126.path = "Wizard_f"
127.path = "Wizard_m"
128.path = "ygirl"
129.path = "Young_f"
130.path = "Young_m"
131.path = "Yulia"
132.path = "Zaebos"
