[800]
path = "worldmap"

[800.0]
path = "Worldmap"

0_0.path  = "sprites/strongpoint_icons.spr"
0_1.path  = "sprites/strongpoint_icons_small.spr"
0_2.path  = "sprites/cleared_flag.spr"
0_3.path  = "sprites/cleared_flag_small.spr"
0_4.path  = "sprites/route_ground.spr"
0_5.path  = "sprites/route_sea.spr"
0_6.path  = "sprites/route_ground_small.spr"
0_7.path  = "sprites/route_sea_small.spr"
0_8.path  = "sprites/pawn_hero.spr"
0_9.path  = "sprites/pawn_hero_leader.spr"
0_10.path = "sprites/pawn_boat.spr"
#0_11.path = "sprites/pawn_hero_?.spr"
0_12.path = "sprites/direction_arrow.spr"
0_13.path = "sprites/cursor.spr"
0_14.path = "sprites/cursor_shadow.spr"

0_18.path = "sprites/stronghold_cleared_mark.spr"
0_19.path = "sprites/stronghold_undiscovered_mark.spr"
0_20.path = "sprites/stronghold_entrance.spr"
0_21.path = "stronghold_positions.xlc"
0_22.path = "route_positions.xlc"

[800.1]
path = "world_atlas.gmo"

[800.256]
path = "worldmap_data"

0_0.path = "stronghold_global_flags.xlc"
