# units (in battle)

[30]
path = "object/unit"

1.path = "Adult_f00"
2.path = "Adult_m00"
3.path = "Aged_f00"
4.path = "Aged_m00"
5.path = "Aloser00"
6.path = "Aloser01"
7.path = "Andoras00"
8.path = "Archer_f00"
9.path = "Archer_f01"
10.path = "Archer_f02"
11.path = "Archer_f03"
12.path = "Archer_f04"
13.path = "Archer_f05"
14.path = "Archer_f06"
15.path = "Archer_f08"
16.path = "Archer_f09"
17.path = "Archer_f13"
18.path = "Archer_m00"
19.path = "Archer_m01"
20.path = "Archer_m02"
21.path = "Archer_m03"
22.path = "Archer_m04"
23.path = "Archer_m05"
24.path = "Archer_m06"
25.path = "Archer_m08"
26.path = "Archer_m09"
27.path = "Archer_m13"
28.path = "Athelstan00"
29.path = "AthelstanCool00"
30.path = "Balbatos00"
31.path = "Balzepho00"
32.path = "Barnas00"
33.path = "BeastTamer_f00"
34.path = "BeastTamer_f01"
35.path = "BeastTamer_f02"
36.path = "BeastTamer_f03"
37.path = "BeastTamer_f04"
38.path = "BeastTamer_f05"
39.path = "BeastTamer_f06"
40.path = "BeastTamer_f08"
41.path = "BeastTamer_f09"
42.path = "BeastTamer_f13"
43.path = "BeastTamer_m00"
44.path = "BeastTamer_m01"
45.path = "BeastTamer_m02"
46.path = "BeastTamer_m03"
47.path = "BeastTamer_m04"
48.path = "BeastTamer_m05"
49.path = "BeastTamer_m06"
50.path = "BeastTamer_m08"
51.path = "BeastTamer_m09"
52.path = "BeastTamer_m13"
53.path = "Belzebuth00"
54.path = "Berserker_f00"
55.path = "Berserker_f01"
56.path = "Berserker_f02"
57.path = "Berserker_f03"
58.path = "Berserker_f04"
59.path = "Berserker_f05"
60.path = "Berserker_f06"
61.path = "Berserker_f08"
62.path = "Berserker_f09"
63.path = "Berserker_f13"
64.path = "Berserker_m00"
65.path = "Berserker_m01"
66.path = "Berserker_m02"
67.path = "Berserker_m03"
68.path = "Berserker_m04"
69.path = "Berserker_m05"
70.path = "Berserker_m06"
71.path = "Berserker_m08"
72.path = "Berserker_m09"
73.path = "Berserker_m13"
74.path = "Boy_m00"
75.path = "Boy2_m00"
76.path = "Branta00"
77.path = "Byan00"
78.path = "Canopus00"
79.path = "Clemont00"
80.path = "Cleric_f00"
81.path = "Cleric_f01"
82.path = "Cleric_f02"
83.path = "Cleric_f03"
84.path = "Cleric_f04"
85.path = "Cleric_f05"
86.path = "Cleric_f06"
87.path = "Cleric_f08"
88.path = "Cleric_f09"
89.path = "Cleric_f13"
90.path = "Cleric_m00"
91.path = "Cleric_m01"
92.path = "Cleric_m02"
93.path = "Cleric_m03"
94.path = "Cleric_m04"
95.path = "Cleric_m05"
96.path = "Cleric_m06"
97.path = "Cleric_m08"
98.path = "Cleric_m09"
99.path = "Cleric_m13"
100.path = "Cockatrice00"
101.path = "Cockatrice02"
102.path = "Cockatrice05"
103.path = "Cockatrice06"
104.path = "Cockatrice08"
105.path = "Cockatrice09"
106.path = "Cockatrice13"
107.path = "Cressida00"
108.path = "Cyclops00"
109.path = "Cyclops06"
110.path = "Cyclops08"
111.path = "Cyclops09"
112.path = "Cyclops10"
113.path = "Cyclops13"
114.path = "Debordes00"
115.path = "Delilah00"
116.path = "DelilahEx00"
117.path = "Deneb00"
118.path = "Deneb01"
119.path = "Denim00"
120.path = "DenimCry00"
121.path = "DenimEnemy00"
122.path = "DenimKing00"
123.path = "DenimLord00"
124.path = "Didarro00"
125.path = "DivineKnight_f00"
126.path = "DivineKnight_f01"
127.path = "DivineKnight_f02"
128.path = "DivineKnight_f03"
129.path = "DivineKnight_f04"
130.path = "DivineKnight_f05"
131.path = "DivineKnight_f06"
132.path = "DivineKnight_f08"
133.path = "DivineKnight_f09"
134.path = "DivineKnight_f13"
135.path = "DivineKnight_m00"
136.path = "DivineKnight_m01"
137.path = "DivineKnight_m02"
138.path = "DivineKnight_m03"
139.path = "DivineKnight_m04"
140.path = "DivineKnight_m05"
141.path = "DivineKnight_m06"
142.path = "DivineKnight_m08"
143.path = "DivineKnight_m09"
144.path = "DivineKnight_m13"
145.path = "Dknight00"
146.path = "Dknight01"
147.path = "Dknight02"
148.path = "Dknight03"
149.path = "Dknight04"
150.path = "Dknight05"
151.path = "Dknight06"
152.path = "Dknight13"
153.path = "Dorgalua00"
154.path = "DorgaluaBefore00"
155.path = "DorgaluaXL00"
156.path = "Dra_Ark00"
157.path = "Dra_Ark01"
158.path = "Dra_Ark02"
159.path = "Dra_Ark03"
160.path = "Dra_Ark04"
161.path = "Dra_Ark05"
162.path = "Dra_Ark06"
163.path = "Dra_Ark08"
164.path = "Dra_Ark09"
165.path = "Dra_Ark10"
166.path = "Dra_Ark11"
167.path = "Dra_Ark12"
168.path = "Dra_Ark13"
169.path = "Dra_Cloud00"
170.path = "Dra_Cloud01"
171.path = "Dra_Cloud02"
172.path = "Dra_Cloud03"
173.path = "Dra_Cloud04"
174.path = "Dra_Cloud05"
175.path = "Dra_Cloud06"
176.path = "Dra_Cloud08"
177.path = "Dra_Cloud09"
178.path = "Dra_Cloud13"
179.path = "Dra_Dark00"
180.path = "Dra_Dark01"
181.path = "Dra_Dark02"
182.path = "Dra_Dark03"
183.path = "Dra_Dark04"
184.path = "Dra_Dark05"
185.path = "Dra_Dark06"
186.path = "Dra_Dark08"
187.path = "Dra_Dark09"
188.path = "Dra_Dark13"
189.path = "Dra_Earth00"
190.path = "Dra_Flame00"
191.path = "Dra_Flood00"
192.path = "Dra_Frost00"
193.path = "Dra_Thunder00"
194.path = "Dragoon_f00"
195.path = "Dragoon_f01"
196.path = "Dragoon_f02"
197.path = "Dragoon_f03"
198.path = "Dragoon_f04"
199.path = "Dragoon_f05"
200.path = "Dragoon_f06"
201.path = "Dragoon_f08"
202.path = "Dragoon_f09"
203.path = "Dragoon_f13"
204.path = "Dragoon_m00"
205.path = "Dragoon_m01"
206.path = "Dragoon_m02"
207.path = "Dragoon_m03"
208.path = "Dragoon_m04"
209.path = "Dragoon_m05"
210.path = "Dragoon_m06"
211.path = "Dragoon_m08"
212.path = "Dragoon_m09"
213.path = "Dragoon_m13"
214.path = "Fairy00"
215.path = "Fairy01"
216.path = "Fairy02"
217.path = "Fairy03"
218.path = "Fairy04"
219.path = "Fairy05"
220.path = "Fairy06"
221.path = "Fairy08"
222.path = "Fairy09"
223.path = "Fairy13"
224.path = "Farfadets00"
225.path = "Forcas00"
226.path = "Ganb00"
227.path = "Gatialo00"
228.path = "Ghost00"
229.path = "Ghost01"
230.path = "Ghost02"
231.path = "Ghost03"
232.path = "Ghost04"
233.path = "Ghost05"
234.path = "Ghost06"
235.path = "Ghost08"
236.path = "Ghost09"
237.path = "Ghost13"
238.path = "Gilbert00"
239.path = "Girl2_f00"
240.path = "Gol_Clay00"
241.path = "Gol_Clay01"
242.path = "Gol_Clay02"
243.path = "Gol_Clay03"
244.path = "Gol_Clay04"
245.path = "Gol_Clay05"
246.path = "Gol_Clay06"
247.path = "Gol_Clay07"
248.path = "Gol_Clay08"
249.path = "Gol_Clay09"
250.path = "Gol_Clay13"
251.path = "Gol_Iron00"
252.path = "Gol_Iron01"
253.path = "Gol_Iron02"
254.path = "Gol_Iron03"
255.path = "Gol_Stone00"
256.path = "Gol_Stone01"
257.path = "Gol_Stone02"
258.path = "Gol_Stone03"
259.path = "Gol_Vulder00"
260.path = "Gol_Vulder01"
261.path = "Gol_Vulder02"
262.path = "Gol_Vulder03"
263.path = "Gremlin00"
264.path = "Gremlin01"
265.path = "Gremlin02"
266.path = "Gremlin03"
267.path = "Gremlin04"
268.path = "Gremlin05"
269.path = "Gremlin06"
270.path = "Gremlin08"
271.path = "Gremlin09"
272.path = "Gremlin13"
273.path = "Gryphon00"
274.path = "Gryphon08"
275.path = "Gryphon09"
276.path = "Gryphon10"
277.path = "Gryphon11"
278.path = "Gryphon12"
279.path = "Gryphon13"
280.path = "Guildus00"
281.path = "Gunner_f00"
282.path = "Gunner_f01"
283.path = "Gunner_f02"
284.path = "Gunner_f03"
285.path = "Gunner_f04"
286.path = "Gunner_f05"
287.path = "Gunner_f06"
288.path = "Gunner_f08"
289.path = "Gunner_f09"
290.path = "Gunner_f13"
291.path = "Gunner_m00"
292.path = "Gunner_m01"
293.path = "Gunner_m02"
294.path = "Gunner_m03"
295.path = "Gunner_m04"
296.path = "Gunner_m05"
297.path = "Gunner_m06"
298.path = "Gunner_m08"
299.path = "Gunner_m09"
300.path = "Gunner_m13"
301.path = "Hawkman00"
302.path = "Hawkman01"
303.path = "Hawkman02"
304.path = "Hawkman03"
305.path = "Hawkman04"
306.path = "Hawkman05"
307.path = "Hawkman06"
308.path = "Hawkman08"
309.path = "Hawkman09"
310.path = "Hawkman13"
311.path = "Hobyrim00"
312.path = "HobyrimYoung00"
313.path = "Hydra00"
314.path = "Hydra01"
315.path = "Hydra04"
316.path = "Hydra08"
317.path = "Hydra09"
318.path = "Hydra13"
319.path = "Jenounes00"
320.path = "Kachua00"
321.path = "KachuaCry00"
322.path = "Kachuadark00"
323.path = "Kachuaprincess00"
324.path = "KachuaQueen00"
325.path = "KachuaShout00"
326.path = "Klaire00"
327.path = "Knight_f00"
328.path = "Knight_f01"
329.path = "Knight_f02"
330.path = "Knight_f03"
331.path = "Knight_f04"
332.path = "Knight_f05"
333.path = "Knight_f06"
334.path = "Knight_f08"
335.path = "Knight_f09"
336.path = "Knight_f13"
337.path = "Knight_m00"
338.path = "Knight_m01"
339.path = "Knight_m02"
340.path = "Knight_m03"
341.path = "Knight_m04"
342.path = "Knight_m05"
343.path = "Knight_m06"
344.path = "Knight_m08"
345.path = "Knight_m09"
346.path = "Knight_m13"
347.path = "Lamia00"
348.path = "Lamia01"
349.path = "Lamia02"
350.path = "Lamia03"
351.path = "Lamia04"
352.path = "Lamia05"
353.path = "Lamia06"
354.path = "Lamia08"
355.path = "Lamia09"
356.path = "Lamia13"
357.path = "LansHami00"
358.path = "LansHamiDisabled00"
359.path = "LansHamiPrison00"
360.path = "LansTar00"
361.path = "Lemonica00"
362.path = "Leonard00"
363.path = "Lich_f00"
364.path = "Lich_f01"
365.path = "Lich_f02"
366.path = "Lich_f03"
367.path = "Lich_f04"
368.path = "Lich_f05"
369.path = "Lich_f06"
370.path = "Lich_f08"
371.path = "Lich_f09"
372.path = "Lich_f13"
373.path = "Lich_m00"
374.path = "Lich_m01"
375.path = "Lich_m02"
376.path = "Lich_m03"
377.path = "Lich_m04"
378.path = "Lich_m05"
379.path = "Lich_m06"
380.path = "Lich_m08"
381.path = "Lich_m09"
382.path = "Lich_m13"
383.path = "Lindl00"
384.path = "Lizardman00"
385.path = "Lizardman01"
386.path = "Lizardman02"
387.path = "Lizardman03"
388.path = "Lizardman04"
389.path = "Lizardman05"
390.path = "Lizardman06"
391.path = "Lizardman08"
392.path = "Lizardman09"
393.path = "Lizardman13"
394.path = "Lukkam00"
395.path = "Luxian00"
396.path = "LuxianEx00"
397.path = "Mannaflora00"
398.path = "Martym00"
399.path = "Mildain00"
400.path = "Mreuva00"
401.path = "Necromancer_f00"
402.path = "Necromancer_f01"
403.path = "Necromancer_f02"
404.path = "Necromancer_f03"
405.path = "Necromancer_f04"
406.path = "Necromancer_f05"
407.path = "Necromancer_f06"
408.path = "Necromancer_f08"
409.path = "Necromancer_f09"
410.path = "Necromancer_f13"
411.path = "Necromancer_m00"
412.path = "Necromancer_m01"
413.path = "Necromancer_m02"
414.path = "Necromancer_m03"
415.path = "Necromancer_m04"
416.path = "Necromancer_m05"
417.path = "Necromancer_m06"
418.path = "Necromancer_m08"
419.path = "Necromancer_m09"
420.path = "Necromancer_m13"
421.path = "Ninja_f00"
422.path = "Ninja_f01"
423.path = "Ninja_f02"
424.path = "Ninja_f03"
425.path = "Ninja_f04"
426.path = "Ninja_f05"
427.path = "Ninja_f06"
428.path = "Ninja_f08"
429.path = "Ninja_f09"
430.path = "Ninja_f13"
431.path = "Ninja_m00"
432.path = "Ninja_m01"
433.path = "Ninja_m02"
434.path = "Ninja_m03"
435.path = "Ninja_m04"
436.path = "Ninja_m05"
437.path = "Ninja_m06"
438.path = "Ninja_m08"
439.path = "Ninja_m09"
440.path = "Ninja_m13"
441.path = "NiseYulia00"
442.path = "Nybbas00"
443.path = "NybbasLich00"
444.path = "Octopus00"
445.path = "Octopus01"
446.path = "Octopus02"
447.path = "Octopus03"
448.path = "Octopus04"
449.path = "Octopus05"
450.path = "Octopus06"
451.path = "Octopus08"
452.path = "Octopus09"
453.path = "Octopus13"
454.path = "Olivia00"
455.path = "Orc00"
456.path = "Orc01"
457.path = "Orc02"
458.path = "Orc03"
459.path = "Orc04"
460.path = "Orc05"
461.path = "Orc06"
462.path = "Orc08"
463.path = "Orc09"
464.path = "Orc13"
465.path = "Orias00"
466.path = "Orlandu00"
467.path = "Oxyones00"
468.path = "Oz00"
469.path = "Ozma00"
470.path = "OzmaCool00"
471.path = "Prancet00"
472.path = "PrancetFilaha00"
473.path = "Presence00"
474.path = "Pumpkin00"
475.path = "Pumpkin01"
476.path = "Pumpkin02"
477.path = "Pumpkin03"
478.path = "Pumpkin04"
479.path = "Pumpkin05"
480.path = "Pumpkin06"
481.path = "Pumpkin07"
482.path = "Pumpkin08"
483.path = "Pumpkin09"
484.path = "Pumpkin13"
485.path = "Radlum00"
486.path = "Ravness00"
487.path = "RavnessBed00"
488.path = "Rodrick00"
489.path = "RodrickBefore00"
490.path = "Ronwey00"
491.path = "Rouge_f00"
492.path = "Rouge_f01"
493.path = "Rouge_f02"
494.path = "Rouge_f03"
495.path = "Rouge_f04"
496.path = "Rouge_f05"
497.path = "Rouge_f06"
498.path = "Rouge_f08"
499.path = "Rouge_f09"
500.path = "Rouge_f13"
501.path = "Rouge_m00"
502.path = "Rouge_m01"
503.path = "Rouge_m02"
504.path = "Rouge_m03"
505.path = "Rouge_m04"
506.path = "Rouge_m05"
507.path = "Rouge_m06"
508.path = "Rouge_m08"
509.path = "Rouge_m09"
510.path = "Rouge_m13"
511.path = "Selye00"
512.path = "Shelley00"
513.path = "ShelleyDisabled00"
514.path = "ShopMaster00"
515.path = "Sisteena00"
516.path = "Skeleton00"
517.path = "Skeleton01"
518.path = "Skeleton02"
519.path = "Skeleton03"
520.path = "Skeleton04"
521.path = "Skeleton05"
522.path = "Skeleton06"
523.path = "Skeleton08"
524.path = "Skeleton09"
525.path = "Skeleton13"
526.path = "Sorcerer_f00"
527.path = "Sorcerer_f01"
528.path = "Sorcerer_f02"
529.path = "Sorcerer_f03"
530.path = "Sorcerer_f04"
531.path = "Sorcerer_f05"
532.path = "Sorcerer_f06"
533.path = "Sorcerer_f08"
534.path = "Sorcerer_f09"
535.path = "Sorcerer_f13"
536.path = "Sorcerer_m00"
537.path = "Sorcerer_m01"
538.path = "Sorcerer_m02"
539.path = "Sorcerer_m03"
540.path = "Sorcerer_m04"
541.path = "Sorcerer_m05"
542.path = "Sorcerer_m06"
543.path = "Sorcerer_m08"
544.path = "Sorcerer_m09"
545.path = "Sorcerer_m13"
546.path = "Sorcerer00"
547.path = "Sorcerer01"
548.path = "Sorcerer02"
549.path = "Sorcerer03"
550.path = "Sorcerer04"
551.path = "Sorcerer05"
552.path = "Sorcerer06"
553.path = "Sorcerer08"
554.path = "Sorcerer09"
555.path = "Sorcerer13"
556.path = "Summoner00"
557.path = "Summoner01"
558.path = "Summoner02"
559.path = "Summoner03"
560.path = "Summoner04"
561.path = "Summoner05"
562.path = "Summoner06"
563.path = "Summoner08"
564.path = "Summoner09"
565.path = "Summoner13"
566.path = "SwordMaster_f00"
567.path = "SwordMaster_f01"
568.path = "SwordMaster_f02"
569.path = "SwordMaster_f03"
570.path = "SwordMaster_f04"
571.path = "SwordMaster_f05"
572.path = "SwordMaster_f06"
573.path = "SwordMaster_f08"
574.path = "SwordMaster_f09"
575.path = "SwordMaster_f13"
576.path = "SwordMaster_m00"
577.path = "SwordMaster_m01"
578.path = "SwordMaster_m02"
579.path = "SwordMaster_m03"
580.path = "SwordMaster_m04"
581.path = "SwordMaster_m05"
582.path = "SwordMaster_m06"
583.path = "SwordMaster_m08"
584.path = "SwordMaster_m09"
585.path = "SwordMaster_m13"
586.path = "TerrorKnight_f00"
587.path = "TerrorKnight_f01"
588.path = "TerrorKnight_f02"
589.path = "TerrorKnight_f03"
590.path = "TerrorKnight_f04"
591.path = "TerrorKnight_f05"
592.path = "TerrorKnight_f06"
593.path = "TerrorKnight_f08"
594.path = "TerrorKnight_f09"
595.path = "TerrorKnight_f13"
596.path = "TerrorKnight_m00"
597.path = "TerrorKnight_m01"
598.path = "TerrorKnight_m02"
599.path = "TerrorKnight_m03"
600.path = "TerrorKnight_m04"
601.path = "TerrorKnight_m05"
602.path = "TerrorKnight_m06"
603.path = "TerrorKnight_m08"
604.path = "TerrorKnight_m09"
605.path = "TerrorKnight_m13"
606.path = "Tiger00"
607.path = "Tristan00"
608.path = "Valkyrie_f00"
609.path = "Valkyrie_f01"
610.path = "Valkyrie_f02"
611.path = "Valkyrie_f03"
612.path = "Valkyrie_f04"
613.path = "Valkyrie_f05"
614.path = "Valkyrie_f06"
615.path = "Valkyrie_f08"
616.path = "Valkyrie_f09"
617.path = "Valkyrie_f13"
618.path = "Valkyrie_m00"
619.path = "Valkyrie_m01"
620.path = "Valkyrie_m02"
621.path = "Valkyrie_m03"
622.path = "Valkyrie_m04"
623.path = "Valkyrie_m05"
624.path = "Valkyrie_m06"
625.path = "Valkyrie_m08"
626.path = "Valkyrie_m09"
627.path = "Valkyrie_m13"
628.path = "Vepar00"
629.path = "Vernotta00"
630.path = "Vice00"
631.path = "ViceDead00"
632.path = "ViceFather00"
633.path = "ViceHostage00"
634.path = "ViceL00"
635.path = "ViceNC00"
636.path = "ViceNCMouth00"
637.path = "Vogras00"
638.path = "Volac00"
639.path = "Warren00"
640.path = "Warrior_f00"
641.path = "Warrior_f01"
642.path = "Warrior_f02"
643.path = "Warrior_f03"
644.path = "Warrior_f04"
645.path = "Warrior_f05"
646.path = "Warrior_f06"
647.path = "Warrior_f08"
648.path = "Warrior_f09"
649.path = "Warrior_f13"
650.path = "Warrior_m00"
651.path = "Warrior_m01"
652.path = "Warrior_m02"
653.path = "Warrior_m03"
654.path = "Warrior_m04"
655.path = "Warrior_m05"
656.path = "Warrior_m06"
657.path = "Warrior_m08"
658.path = "Warrior_m09"
659.path = "Warrior_m13"
660.path = "Wizard_f00"
661.path = "Wizard_f01"
662.path = "Wizard_f02"
663.path = "Wizard_f03"
664.path = "Wizard_f04"
665.path = "Wizard_f05"
666.path = "Wizard_f06"
667.path = "Wizard_f08"
668.path = "Wizard_f09"
669.path = "Wizard_f13"
670.path = "Wizard_m00"
671.path = "Wizard_m01"
672.path = "Wizard_m02"
673.path = "Wizard_m03"
674.path = "Wizard_m04"
675.path = "Wizard_m05"
676.path = "Wizard_m06"
677.path = "Wizard_m08"
678.path = "Wizard_m09"
679.path = "Wizard_m13"
680.path = "XXapan00"
681.path = "Yobikao00"
682.path = "Yobikao01"
683.path = "Yobikao02"
684.path = "Yobikao03"
685.path = "Yobikao04"
686.path = "Yobikao05"
687.path = "Yobikao06"
688.path = "Yobikao07"
689.path = "Yobikao08"
690.path = "Yobikao09"
691.path = "Yobikao10"
692.path = "Young_f00"
693.path = "Young_m00"
694.path = "Yulia00"
695.path = "Yulia05"
696.path = "Zaebos_death00"
697.path = "Zaebos_fop00"
698.path = "Zaebos00"
699.path = "Zapan00"
