[850]
path = "worldmap/MMAP"
obfuscated = true


[850.101]
path = "almorica_castle"


[850.201]
path = "coritanae_keep"


[850.301]
path = "brigantys_castle"


[850.401]
path = "phidoch_castle"


[850.501]
path = "barnicia_castle"


[850.601]
path = "royal_city_of_heim"


[850.701]
path = "hanging_gardens"


[850.801]
path = "heart_of_the_gardens"


[850.901]
path = "ndamsa_fortress"


[850.1001]
path = "gecho_fortress"


[850.1101]
path = "qadriga_fortress"


[850.1201]
path = "geyld_fortress"


[850.1301]
path = "boed_fortress"


[850.1401]
path = "lhazan_fortress"


[850.1501]
path = "phorampa_wildwood/1"


[850.1502]
path = "phorampa_wildwood/2"


[850.1503]
path = "phorampa_wildwood/3"


[850.2201]
path = "pirates_graveyard/1"


[850.2202]
path = "pirates_graveyard/2"


[850.2401]
path = "golyat"


[850.2501]
path = "arkhaiopolis_of_rime"


[850.2601]
path = "palace_of_the_dead/2601"


[850.2602]
path = "palace_of_the_dead/2602"


[850.2603]
path = "palace_of_the_dead/2603"


[850.2604]
path = "palace_of_the_dead/2604"


[850.2701]
path = "palace_of_the_dead/2701"


[850.2702]
path = "palace_of_the_dead/2702"


[850.2703]
path = "palace_of_the_dead/2703"


[850.2801]
path = "palace_of_the_dead/2801"


[850.2802]
path = "palace_of_the_dead/2802"


[850.2803]
path = "palace_of_the_dead/2803"


[850.2901]
path = "palace_of_the_dead/2901"


[850.2902]
path = "palace_of_the_dead/2902"


[850.2903]
path = "palace_of_the_dead/2903"


[850.2904]
path = "palace_of_the_dead/2904"


[850.3001]
path = "palace_of_the_dead/3001"


[850.3002]
path = "palace_of_the_dead/3002"


[850.3003]
path = "palace_of_the_dead/3003"


[850.3004]
path = "palace_of_the_dead/3004"


[850.3101]
path = "san_bronsa_ruins/1"


[850.3102]
path = "san_bronsa_ruins/2"


[850.3103]
path = "san_bronsa_ruins/3"


[850.3104]
path = "san_bronsa_ruins/4"


[850.3105]
path = "san_bronsa_ruins/5"


[850.3106]
path = "san_bronsa_ruins/6"

