[1000.1]
3.path = "equipment.xlc"
7.path = "class_text.xlc"
9.path = "map_parties.xlc" # not sure if completely accurate
20.path = "random_character_names.xlc"
27.path = "equipment_text.xlc"
28.path = "factions.xlc"
37.path = "map_spawn_coordinates.xlc"
38.path = "battle_death_messages.xlc"
39.path = "battle_skill_messages.xlc"
40.path = "battle_notification_messages.xlc"
