[400]
path = "sounds"

1.path  = "bgm/bgm_1.scd"
2.path  = "bgm/bgm_2.scd"
3.path  = "bgm/bgm_3.scd"
4.path  = "bgm/bgm_4.scd"
5.path  = "bgm/bgm_5.scd"
6.path  = "bgm/bgm_6.scd"
7.path  = "bgm/bgm_7.scd"
8.path  = "bgm/bgm_8.scd"
9.path  = "bgm/bgm_9.scd"
10.path = "bgm/bgm_10.scd"
11.path = "bgm/bgm_11.scd"
12.path = "bgm/bgm_12.scd"
13.path = "bgm/bgm_13.scd"
14.path = "bgm/bgm_14.scd"
15.path = "bgm/bgm_15.scd"
16.path = "bgm/bgm_16.scd"
17.path = "bgm/bgm_17.scd"
18.path = "bgm/bgm_18.scd"
19.path = "bgm/bgm_19.scd"
20.path = "bgm/bgm_20.scd"
21.path = "bgm/bgm_21.scd"
22.path = "bgm/bgm_22.scd"
23.path = "bgm/bgm_23.scd"
24.path = "bgm/bgm_24.scd"
25.path = "bgm/bgm_25.scd"
26.path = "bgm/bgm_26.scd"
27.path = "bgm/bgm_27.scd"
28.path = "bgm/bgm_28.scd"
29.path = "bgm/bgm_29.scd"
30.path = "bgm/bgm_30.scd"
31.path = "bgm/bgm_31.scd"
32.path = "bgm/bgm_32.scd"
33.path = "bgm/bgm_33.scd"
34.path = "bgm/bgm_34.scd"
35.path = "bgm/bgm_35.scd"
36.path = "bgm/bgm_36.scd"
37.path = "bgm/bgm_37.scd"
38.path = "bgm/bgm_38.scd"
39.path = "bgm/bgm_39.scd"
40.path = "bgm/bgm_40.scd"
41.path = "bgm/bgm_41.scd"
42.path = "bgm/bgm_42.scd"
43.path = "bgm/bgm_43.scd"
44.path = "bgm/bgm_44.scd"
45.path = "bgm/bgm_45.scd"
46.path = "bgm/bgm_46.scd"
47.path = "bgm/bgm_47.scd"
48.path = "bgm/bgm_48.scd"
49.path = "bgm/bgm_49.scd"
50.path = "bgm/bgm_50.scd"
51.path = "bgm/bgm_51.scd"
52.path = "bgm/bgm_52.scd"
53.path = "bgm/bgm_53.scd"
54.path = "bgm/bgm_54.scd"
55.path = "bgm/bgm_55.scd"
56.path = "bgm/bgm_56.scd"
57.path = "bgm/bgm_57.scd"
58.path = "bgm/bgm_58.scd"
59.path = "bgm/bgm_59.scd"
60.path = "bgm/bgm_60.scd"
61.path = "bgm/bgm_61.scd"
62.path = "bgm/bgm_62.scd"
63.path = "bgm/bgm_63.scd"
64.path = "bgm/bgm_64.scd"
65.path = "bgm/bgm_65.scd"
66.path = "bgm/bgm_66.scd"
67.path = "bgm/bgm_67.scd"
68.path = "bgm/bgm_68.scd"
69.path = "bgm/bgm_69.scd"
70.path = "bgm/bgm_70.scd"
