[800]
path = "ui/world_map"

[800.0]
0_0.path  = "sprites/strongpoint_icons.sprite"
0_1.path  = "sprites/strongpoint_icons_small.sprite"
0_2.path  = "sprites/cleared_flag.sprite"
0_3.path  = "sprites/cleared_flag_small.sprite"
0_4.path  = "sprites/route_ground.sprite"
0_5.path  = "sprites/route_sea.sprite"
0_6.path  = "sprites/route_ground_small.sprite"
0_7.path  = "sprites/route_sea_small.sprite"
0_8.path  = "sprites/pawn_hero.sprite"
0_9.path  = "sprites/pawn_hero_leader.sprite"
0_10.path = "sprites/pawn_boat.sprite"
#0_11.path = "sprites/pawn_hero_?.sprite"
0_12.path = "sprites/direction_arrow.sprite"
0_13.path = "sprites/cursor.sprite"
0_14.path = "sprites/cursor_shadow.sprite"

0_18.path = "sprites/stronghold_cleared_mark.sprite"
0_19.path = "sprites/stronghold_undiscovered_mark.sprite"
0_20.path = "sprites/stronghold_entrance.sprite"
0_21.path = "stronghold_positions.xlc"
0_22.path = "route_positions.xlc"

[800.1]
path = "world_atlas.gmo"

[800.256]
path = "strongholds"

0_0.path = "stronghold_global_flags.xlc"
