[850]
path = "ui/strongholds"


[850.101]
path = "almorica_castle"

0_16.path = "map_icons/16.spr"
0_28.path = "map_icons/28.spr"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.201]
path = "coritanae_keep"

0_17.path = "map_icons/17.spr"
0_32.path = "map_icons/32.spr"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.301]
path = "brigantys_castle"

0_18.path = "map_icons/18.spr"
0_19.path = "map_icons/19.spr"
0_31.path = "map_icons/31.spr"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.401]
path = "phidoch_castle"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.501]
path = "barnicia_castle"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.601]
path = "royal_city_of_heim"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.701]
path = "hanging_gardens"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.801]
path = "heart_of_the_gardens"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.901]
path = "ndamsa_fortress"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.1001]
path = "gecho_fortress"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.1101]
path = "qadriga_fortress"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.1201]
path = "geyld_fortress"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.1301]
path = "boed_fortress"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.1401]
path = "lhazan_fortress"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.1501]
path = "phorampa_wildwood/1"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.1502]
path = "phorampa_wildwood/2"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.1503]
path = "phorampa_wildwood/3"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.1801]
path = "mount_weobry"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2201]
path = "pirates_graveyard/1"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2202]
path = "pirates_graveyard/2"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2401]
path = "golyat"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2501]
path = "arkhaiopolis_of_rime"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2601]
path = "palace_of_the_dead/2601"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2602]
path = "palace_of_the_dead/2602"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2603]
path = "palace_of_the_dead/2603"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2604]
path = "palace_of_the_dead/2604"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2701]
path = "palace_of_the_dead/2701"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2702]
path = "palace_of_the_dead/2702"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2703]
path = "palace_of_the_dead/2703"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2801]
path = "palace_of_the_dead/2801"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2802]
path = "palace_of_the_dead/2802"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2803]
path = "palace_of_the_dead/2803"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2901]
path = "palace_of_the_dead/2901"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2902]
path = "palace_of_the_dead/2902"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2903]
path = "palace_of_the_dead/2903"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.2904]
path = "palace_of_the_dead/2904"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.3001]
path = "palace_of_the_dead/3001"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.3002]
path = "palace_of_the_dead/3002"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.3003]
path = "palace_of_the_dead/3003"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.3004]
path = "palace_of_the_dead/3004"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.3101]
path = "san_bronsa_ruins/1"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.3102]
path = "san_bronsa_ruins/2"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.3103]
path = "san_bronsa_ruins/3"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.3104]
path = "san_bronsa_ruins/4"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.3105]
path = "san_bronsa_ruins/5"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"


[850.3106]
path = "san_bronsa_ruins/6"

0_24576.path = "title.spr"
0_24577.path = "background.spr"

0_32767.path = "stronghold.xlc"
