# C2b

[903]
path = "chapters/chapter_2/law"


[903.1]
path = "C2b_ST_001"

0_6001.path  = "scene_2b_0.scene"
0_38769.path = "scene_2b_0.resources"


[903.10]
path = "C2b_ST_010"

0_6002.path  = "scene_2b_1.scene"
0_38770.path = "scene_2b_1.resources"


[903.20]
path = "C2b_ST_020"

0_6003.path  = "scene_2b_2.scene"
0_38771.path = "scene_2b_2.resources"


[903.30]
path = "C2b_ST_030"

0_6004.path  = "scene_2b_3.scene"
0_38772.path = "scene_2b_3.resources"
1_6004.path  = "scene_2b_3.messages"


[903.40]
path = "C2b_ST_040"

0_6005.path  = "scene_2b_4.scene"
0_38773.path = "scene_2b_4.resources"
1_6005.path  = "scene_2b_4.messages"


[903.50]
path = "C2b_ST_050"

0_6006.path  = "scene_2b_5.scene"
0_38774.path = "scene_2b_5.resources"
1_6006.path  = "scene_2b_5.messages"

0_6007.path  = "scene_2b_6.scene"
0_38775.path = "scene_2b_6.resources"
1_6007.path  = "scene_2b_6.messages"


[903.60]
path = "C2b_ST_060"

0_6012.path  = "scene_2b_7.scene"
0_38780.path = "scene_2b_7.resources"
1_6012.path  = "scene_2b_7.messages"

0_6013.path  = "scene_2b_8.scene"
0_38781.path = "scene_2b_8.resources"
1_6013.path  = "scene_2b_8.messages"

0_6014.path  = "scene_2b_9.scene"
0_38782.path = "scene_2b_9.resources"
1_6014.path  = "scene_2b_9.messages"

0_6015.path  = "scene_2b_10.scene"
0_38783.path = "scene_2b_10.resources"
1_6015.path  = "scene_2b_10.messages"

0_6016.path  = "scene_2b_11.scene"
0_38784.path = "scene_2b_11.resources"
1_6016.path  = "scene_2b_11.messages"


[903.70]
path = "C2b_ST_070"

0_6020.path  = "scene_2b_12.scene"
0_38788.path = "scene_2b_12.resources"
1_6020.path  = "scene_2b_12.messages"

0_6021.path  = "scene_2b_13.scene"
0_38789.path = "scene_2b_13.resources"
1_6021.path  = "scene_2b_13.messages"


[903.80]
path = "C2b_ST_080"

0_6022.path  = "scene_2b_14.scene"
0_38790.path = "scene_2b_14.resources"
1_6022.path  = "scene_2b_14.messages"

0_6023.path  = "scene_2b_15.scene"
0_38791.path = "scene_2b_15.resources"
1_6023.path  = "scene_2b_15.messages"


[903.90]
path = "C2b_ST_090"

0_6024.path  = "scene_2b_16.scene"
0_38792.path = "scene_2b_16.resources"
1_6024.path  = "scene_2b_16.messages"


[903.100]
path = "C2b_ST_100"

0_6026.path  = "scene_2b_17.scene"
0_38794.path = "scene_2b_17.resources"
1_6026.path  = "scene_2b_17.messages"

0_6027.path  = "scene_2b_18.scene"
0_38795.path = "scene_2b_18.resources"
1_6027.path  = "scene_2b_18.messages"

0_6028.path  = "scene_2b_19.scene"
0_38796.path = "scene_2b_19.resources"
1_6028.path  = "scene_2b_19.messages"

0_6029.path  = "scene_2b_20.scene"
0_38797.path = "scene_2b_20.resources"
1_6029.path  = "scene_2b_20.messages"

0_6030.path  = "scene_2b_21.scene"
0_38798.path = "scene_2b_21.resources"
1_6030.path  = "scene_2b_21.messages"

0_6031.path  = "scene_2b_22.scene"
0_38799.path = "scene_2b_22.resources"
1_6031.path  = "scene_2b_22.messages"

0_6032.path  = "scene_2b_23.scene"
0_38800.path = "scene_2b_23.resources"
1_6032.path  = "scene_2b_23.messages"

0_6033.path  = "scene_2b_24.scene"
0_38801.path = "scene_2b_24.resources"
1_6033.path  = "scene_2b_24.messages"

0_6034.path  = "scene_2b_25.scene"
0_38802.path = "scene_2b_25.resources"
1_6034.path  = "scene_2b_25.messages"


[903.110]
path = "C2b_ST_110"

0_6035.path  = "scene_2b_26.scene"
0_38803.path = "scene_2b_26.resources"
1_6035.path  = "scene_2b_26.messages"


[903.120]
path = "C2b_ST_120"

0_6036.path  = "scene_2b_27.scene"
0_38804.path = "scene_2b_27.resources"
1_6036.path  = "scene_2b_27.messages"

0_6037.path  = "scene_2b_28.scene"
0_38805.path = "scene_2b_28.resources"
1_6037.path  = "scene_2b_28.messages"

0_6038.path  = "scene_2b_29.scene"
0_38806.path = "scene_2b_29.resources"
1_6038.path  = "scene_2b_29.messages"

0_6040.path  = "scene_2b_30.scene"
0_38808.path = "scene_2b_30.resources"
1_6040.path  = "scene_2b_30.messages"

0_6041.path  = "scene_2b_31.scene"
0_38809.path = "scene_2b_31.resources"
1_6041.path  = "scene_2b_31.messages"

0_6042.path  = "scene_2b_32.scene"
0_38810.path = "scene_2b_32.resources"
1_6042.path  = "scene_2b_32.messages"

0_6045.path  = "scene_2b_33.scene"
0_38813.path = "scene_2b_33.resources"
1_6045.path  = "scene_2b_33.messages"


[903.130]
path = "C2b_ST_130"

0_6048.path  = "scene_2b_34.scene"
0_38816.path = "scene_2b_34.resources"
1_6048.path  = "scene_2b_34.messages"

0_6049.path  = "scene_2b_35.scene"
0_38817.path = "scene_2b_35.resources"
1_6049.path  = "scene_2b_35.messages"

0_6050.path  = "scene_2b_36.scene"
0_38818.path = "scene_2b_36.resources"
1_6050.path  = "scene_2b_36.messages"

0_6051.path  = "scene_2b_37.scene"
0_38819.path = "scene_2b_37.resources"
1_6051.path  = "scene_2b_37.messages"

0_6052.path  = "scene_2b_38.scene"
0_38820.path = "scene_2b_38.resources"
1_6052.path  = "scene_2b_38.messages"

0_6053.path  = "scene_2b_39.scene"
0_38821.path = "scene_2b_39.resources"
1_6053.path  = "scene_2b_39.messages"

0_6054.path  = "scene_2b_40.scene"
0_38822.path = "scene_2b_40.resources"
1_6054.path  = "scene_2b_40.messages"

0_6055.path  = "scene_2b_41.scene"
0_38823.path = "scene_2b_41.resources"
1_6055.path  = "scene_2b_41.messages"

0_6056.path  = "scene_2b_42.scene"
0_38824.path = "scene_2b_42.resources"
1_6056.path  = "scene_2b_42.messages"


[903.140]
path = "C2b_ST_140"

0_6058.path  = "scene_2b_43.scene"
0_38826.path = "scene_2b_43.resources"
1_6058.path  = "scene_2b_43.messages"


[903.150]
path = "C2b_ST_150"

0_6059.path  = "scene_2b_44.scene"
0_38827.path = "scene_2b_44.resources"
1_6059.path  = "scene_2b_44.messages"


[903.160]
path = "C2b_ST_160"

0_6060.path  = "scene_2b_45.scene"
0_38828.path = "scene_2b_45.resources"
1_6060.path  = "scene_2b_45.messages"

0_6061.path  = "scene_2b_46.scene"
0_38829.path = "scene_2b_46.resources"
1_6061.path  = "scene_2b_46.messages"

0_6062.path  = "scene_2b_47.scene"
0_38830.path = "scene_2b_47.resources"
1_6062.path  = "scene_2b_47.messages"

0_6063.path  = "scene_2b_48.scene"
0_38831.path = "scene_2b_48.resources"
1_6063.path  = "scene_2b_48.messages"

0_6064.path  = "scene_2b_49.scene"
0_38832.path = "scene_2b_49.resources"
1_6064.path  = "scene_2b_49.messages"

0_6065.path  = "scene_2b_50.scene"
0_38833.path = "scene_2b_50.resources"
1_6065.path  = "scene_2b_50.messages"


[903.170]
path = "C2b_ST_170"

0_6066.path  = "scene_2b_51.scene"
0_38834.path = "scene_2b_51.resources"
1_6066.path  = "scene_2b_51.messages"


[903.180]
path = "C2b_ST_180"

0_6067.path  = "scene_2b_52.scene"
0_38835.path = "scene_2b_52.resources"
1_6067.path  = "scene_2b_52.messages"

0_6069.path  = "scene_2b_53.scene"
0_38837.path = "scene_2b_53.resources"
1_6069.path  = "scene_2b_53.messages"

0_6070.path  = "scene_2b_54.scene"
0_38838.path = "scene_2b_54.resources"
1_6070.path  = "scene_2b_54.messages"

0_6071.path  = "scene_2b_55.scene"
0_38839.path = "scene_2b_55.resources"
1_6071.path  = "scene_2b_55.messages"


[903.190]
path = "C2b_ST_190"

0_6072.path  = "scene_2b_56.scene"
0_38840.path = "scene_2b_56.resources"
1_6072.path  = "scene_2b_56.messages"

0_6073.path  = "scene_2b_57.scene"
0_38841.path = "scene_2b_57.resources"
1_6073.path  = "scene_2b_57.messages"

0_6074.path  = "scene_2b_58.scene"
0_38842.path = "scene_2b_58.resources"
1_6074.path  = "scene_2b_58.messages"

0_6075.path  = "scene_2b_59.scene"
0_38843.path = "scene_2b_59.resources"
1_6075.path  = "scene_2b_59.messages"

0_6076.path  = "scene_2b_60.scene"
0_38844.path = "scene_2b_60.resources"
1_6076.path  = "scene_2b_60.messages"

0_6077.path  = "scene_2b_61.scene"
0_38845.path = "scene_2b_61.resources"
1_6077.path  = "scene_2b_61.messages"

0_6078.path  = "scene_2b_62.scene"
0_38846.path = "scene_2b_62.resources"
1_6078.path  = "scene_2b_62.messages"

0_6079.path  = "scene_2b_63.scene"
0_38847.path = "scene_2b_63.resources"
1_6079.path  = "scene_2b_63.messages"

0_6080.path  = "scene_2b_64.scene"
0_38848.path = "scene_2b_64.resources"
1_6080.path  = "scene_2b_64.messages"

0_6081.path  = "scene_2b_65.scene"
0_38849.path = "scene_2b_65.resources"
1_6081.path  = "scene_2b_65.messages"

0_6082.path  = "scene_2b_66.scene"
0_38850.path = "scene_2b_66.resources"
1_6082.path  = "scene_2b_66.messages"


[903.195]
path = "C2b_ST_195"

0_6083.path  = "scene_2b_67.scene"
0_38851.path = "scene_2b_67.resources"


[903.196]
path = "C2b_ST_196"

0_6084.path  = "scene_2b_68.scene"
0_38852.path = "scene_2b_68.resources"
1_6084.path  = "scene_2b_68.messages"


[903.197]
path = "C2b_ST_197"

0_6085.path  = "scene_2b_69.scene"
0_38853.path = "scene_2b_69.resources"
1_6085.path  = "scene_2b_69.messages"


[903.200]
path = "C2b_ST_200"


[903.210]
path = "C2b_ST_210"

0_6088.path  = "scene_2b_70.scene"
0_38856.path = "scene_2b_70.resources"


[903.220]
path = "C2b_ST_220"

0_6089.path  = "scene_2b_71.scene"
0_38857.path = "scene_2b_71.resources"
1_6089.path  = "scene_2b_71.messages"


[903.230]
path = "C2b_ST_230"

0_6090.path  = "scene_2b_72.scene"
0_38858.path = "scene_2b_72.resources"
1_6090.path  = "scene_2b_72.messages"

0_6091.path  = "scene_2b_73.scene"
0_38859.path = "scene_2b_73.resources"
1_6091.path  = "scene_2b_73.messages"


[903.240]
path = "C2b_ST_240"

0_6092.path  = "scene_2b_74.scene"
0_38860.path = "scene_2b_74.resources"
1_6092.path  = "scene_2b_74.messages"

0_6093.path  = "scene_2b_75.scene"
0_38861.path = "scene_2b_75.resources"
1_6093.path  = "scene_2b_75.messages"


[903.250]
path = "C2b_ST_250"

0_6094.path  = "scene_2b_76.scene"
0_38862.path = "scene_2b_76.resources"
1_6094.path  = "scene_2b_76.messages"


[903.260]
path = "C2b_ST_260"

0_6095.path  = "scene_2b_77.scene"
0_38863.path = "scene_2b_77.resources"
1_6095.path  = "scene_2b_77.messages"

0_6098.path  = "scene_2b_78.scene"
0_38866.path = "scene_2b_78.resources"
1_6098.path  = "scene_2b_78.messages"

0_6101.path  = "scene_2b_90.scene"
0_38869.path = "scene_2b_90.resources"
1_6101.path  = "scene_2b_90.messages"

0_6102.path  = "scene_2b_91.scene"
0_38870.path = "scene_2b_91.resources"
1_6102.path  = "scene_2b_91.messages"

0_6103.path  = "scene_2b_79.scene"
0_38871.path = "scene_2b_79.resources"
1_6103.path  = "scene_2b_79.messages"

0_6104.path  = "scene_2b_80.scene"
0_38872.path = "scene_2b_80.resources"
1_6104.path  = "scene_2b_80.messages"

0_6105.path  = "scene_2b_81.scene"
0_38873.path = "scene_2b_81.resources"
1_6105.path  = "scene_2b_81.messages"

0_6106.path  = "scene_2b_82.scene"
0_38874.path = "scene_2b_82.resources"
1_6106.path  = "scene_2b_82.messages"

0_6107.path  = "scene_2b_83.scene"
0_38875.path = "scene_2b_83.resources"
1_6107.path  = "scene_2b_83.messages"

0_6108.path  = "scene_2b_111.scene"
0_38876.path = "scene_2b_111.resources"
1_6108.path  = "scene_2b_111.messages"

0_6109.path  = "scene_2b_112.scene"
0_38877.path = "scene_2b_112.resources"
1_6109.path  = "scene_2b_112.messages"

0_6110.path  = "scene_2b_113.scene"
0_38878.path = "scene_2b_113.resources"
1_6110.path  = "scene_2b_113.messages"

0_6111.path  = "scene_2b_84.scene"
0_38879.path = "scene_2b_84.resources"
1_6111.path  = "scene_2b_84.messages"

0_6114.path  = "scene_2b_85.scene"
0_38882.path = "scene_2b_85.resources"
1_6114.path  = "scene_2b_85.messages"


[903.270]
path = "C2b_ST_270"

0_6117.path  = "scene_2b_87.scene"
0_38885.path = "scene_2b_87.resources"


[903.280]
path = "C2b_ST_280"

0_6118.path  = "scene_2b_88.scene"
0_38886.path = "scene_2b_88.resources"


[903.290]
path = "C2b_ST_290"

0_6119.path  = "scene_2b_89.scene"
0_38887.path = "scene_2b_89.resources"
1_6119.path  = "scene_2b_89.messages"


[903.300]
path = "C2b_ST_300"

0_6123.path  = "scene_2b_100.scene"
0_38891.path = "scene_2b_100.resources"
1_6123.path  = "scene_2b_100.messages"

0_6124.path  = "scene_2b_101.scene"
0_38892.path = "scene_2b_101.resources"
1_6124.path  = "scene_2b_101.messages"

0_6125.path  = "scene_2b_102.scene"
0_38893.path = "scene_2b_102.resources"
1_6125.path  = "scene_2b_102.messages"

0_6126.path  = "scene_2b_103.scene"
0_38894.path = "scene_2b_103.resources"
1_6126.path  = "scene_2b_103.messages"

0_6127.path  = "scene_2b_104.scene"
0_38895.path = "scene_2b_104.resources"
1_6127.path  = "scene_2b_104.messages"

0_6128.path  = "scene_2b_105.scene"
0_38896.path = "scene_2b_105.resources"
1_6128.path  = "scene_2b_105.messages"

0_6129.path  = "scene_2b_107.scene"
0_38897.path = "scene_2b_107.resources"
1_6129.path  = "scene_2b_107.messages"

0_6130.path  = "scene_2b_108.scene"
0_38898.path = "scene_2b_108.resources"
1_6130.path  = "scene_2b_108.messages"

0_6131.path  = "scene_2b_109.scene"
0_38899.path = "scene_2b_109.resources"
1_6131.path  = "scene_2b_109.messages"


[903.310]
path = "C2b_ST_310"

0_6132.path  = "scene_2b_110.scene"
0_38900.path = "scene_2b_110.resources"
1_6132.path  = "scene_2b_110.messages"


[903.311]
path = "C2b_ST_311"


[903.320]
path = "C2b_ST_320"


[903.321]
path = "C2b_ST_321"


[903.322]
path = "C2b_ST_322"


[903.323]
path = "C2b_ST_323"


[903.324]
path = "C2b_ST_324"


[903.325]
path = "C2b_ST_325"


[903.326]
path = "C2b_ST_326"


[903.327]
path = "C2b_ST_327"
