# C3c

[906]
path = "chapters/chapter_3/law"


[906.1]
path = "C3c_ST_001"

0_15001.path = "scene_3c_0.script"
0_47769.path = "scene_3c_0.resources"


[906.10]
path = "C3c_ST_010"

0_15002.path = "scene_3c_1.script"
0_47770.path = "scene_3c_1.resources"
1_15002.path = "scene_3c_1.messages"


[906.20]
path = "C3c_ST_020"

0_15003.path = "scene_3c_2.script"
0_47771.path = "scene_3c_2.resources"
1_15003.path = "scene_3c_2.messages"


[906.30]
path = "C3c_ST_030"

0_15004.path = "scene_3c_3.script"
0_47772.path = "scene_3c_3.resources"
1_15004.path = "scene_3c_3.messages"


[906.40]
path = "C3c_ST_040"

0_15005.path = "scene_3c_4.script"
0_47773.path = "scene_3c_4.resources"
1_15005.path = "scene_3c_4.messages"


[906.50]
path = "C3c_ST_050"

0_15009.path = "scene_3c_5.script"
0_47777.path = "scene_3c_5.resources"
1_15009.path = "scene_3c_5.messages"


[906.60]
path = "C3c_ST_060"

0_15010.path = "scene_3c_6.script"
0_47778.path = "scene_3c_6.resources"
1_15010.path = "scene_3c_6.messages"

0_15011.path = "scene_3c_7.script"
0_47779.path = "scene_3c_7.resources"
1_15011.path = "scene_3c_7.messages"

0_15012.path = "scene_3c_8.script"
0_47780.path = "scene_3c_8.resources"
1_15012.path = "scene_3c_8.messages"

0_15013.path = "scene_3c_9.script"
0_47781.path = "scene_3c_9.resources"
1_15013.path = "scene_3c_9.messages"


[906.70]
path = "C3c_ST_070"

0_15014.path = "scene_3c_10.script"
0_47782.path = "scene_3c_10.resources"


[906.80]
path = "C3c_ST_080"

0_15015.path = "scene_3c_11.script"
0_47783.path = "scene_3c_11.resources"
1_15015.path = "scene_3c_11.messages"

0_15016.path = "scene_3c_12.script"
0_47784.path = "scene_3c_12.resources"
1_15016.path = "scene_3c_12.messages"

0_15017.path = "scene_3c_13.script"
0_47785.path = "scene_3c_13.resources"
1_15017.path = "scene_3c_13.messages"

0_15018.path = "scene_3c_14.script"
0_47786.path = "scene_3c_14.resources"
1_15018.path = "scene_3c_14.messages"


[906.90]
path = "C3c_ST_090"

0_15019.path = "scene_3c_15.script"
0_47787.path = "scene_3c_15.resources"
1_15019.path = "scene_3c_15.messages"

0_15020.path = "scene_3c_16.script"
0_47788.path = "scene_3c_16.resources"
1_15020.path = "scene_3c_16.messages"

0_15021.path = "scene_3c_17.script"
0_47789.path = "scene_3c_17.resources"
1_15021.path = "scene_3c_17.messages"

0_15022.path = "scene_3c_18.script"
0_47790.path = "scene_3c_18.resources"
1_15022.path = "scene_3c_18.messages"


[906.100]
path = "C3c_ST_100"

0_15023.path = "scene_3c_19.script"
0_47791.path = "scene_3c_19.resources"
1_15023.path = "scene_3c_19.messages"


[906.110]
path = "C3c_ST_110"

0_15024.path = "scene_3c_20.script"
0_47792.path = "scene_3c_20.resources"
1_15024.path = "scene_3c_20.messages"

0_15025.path = "scene_3c_21.script"
0_47793.path = "scene_3c_21.resources"
1_15025.path = "scene_3c_21.messages"

0_15026.path = "scene_3c_22.script"
0_47794.path = "scene_3c_22.resources"
1_15026.path = "scene_3c_22.messages"

0_15027.path = "scene_3c_23.script"
0_47795.path = "scene_3c_23.resources"
1_15027.path = "scene_3c_23.messages"

0_15028.path = "scene_3c_24.script"
0_47796.path = "scene_3c_24.resources"
1_15028.path = "scene_3c_24.messages"


[906.120]
path = "C3c_ST_120"

0_15029.path = "scene_3c_25.script"
0_47797.path = "scene_3c_25.resources"
1_15029.path = "scene_3c_25.messages"

0_15030.path = "scene_3c_26.script"
0_47798.path = "scene_3c_26.resources"
1_15030.path = "scene_3c_26.messages"

0_15034.path = "scene_3c_27.script"
0_47802.path = "scene_3c_27.resources"
1_15034.path = "scene_3c_27.messages"


[906.130]
path = "C3c_ST_130"

0_15039.path = "scene_3c_28.script"
0_47807.path = "scene_3c_28.resources"
1_15039.path = "scene_3c_28.messages"

0_15040.path = "scene_3c_29.script"
0_47808.path = "scene_3c_29.resources"
1_15040.path = "scene_3c_29.messages"

0_15041.path = "scene_3c_30.script"
0_47809.path = "scene_3c_30.resources"
1_15041.path = "scene_3c_30.messages"

0_15042.path = "scene_3c_31.script"
0_47810.path = "scene_3c_31.resources"
1_15042.path = "scene_3c_31.messages"

0_15043.path = "scene_3c_32.script"
0_47811.path = "scene_3c_32.resources"
1_15043.path = "scene_3c_32.messages"

0_15044.path = "scene_3c_33.script"
0_47812.path = "scene_3c_33.resources"
1_15044.path = "scene_3c_33.messages"

0_15045.path = "scene_3c_34.script"
0_47813.path = "scene_3c_34.resources"
1_15045.path = "scene_3c_34.messages"


[906.140]
path = "C3c_ST_140"

0_15046.path = "scene_3c_35.script"
0_47814.path = "scene_3c_35.resources"
1_15046.path = "scene_3c_35.messages"

0_15047.path = "scene_3c_36.script"
0_47815.path = "scene_3c_36.resources"
1_15047.path = "scene_3c_36.messages"

0_15048.path = "scene_3c_37.script"
0_47816.path = "scene_3c_37.resources"
1_15048.path = "scene_3c_37.messages"

0_15049.path = "scene_3c_38.script"
0_47817.path = "scene_3c_38.resources"
1_15049.path = "scene_3c_38.messages"


[906.150]
path = "C3c_ST_150"

0_15051.path = "scene_3c_39.script"
0_47819.path = "scene_3c_39.resources"


[906.160]
path = "C3c_ST_160"

0_15053.path = "scene_3c_40.script"
0_47821.path = "scene_3c_40.resources"
1_15053.path = "scene_3c_40.messages"

0_15054.path = "scene_3c_41.script"
0_47822.path = "scene_3c_41.resources"
1_15054.path = "scene_3c_41.messages"


[906.170]
path = "C3c_ST_170"

0_15055.path = "scene_3c_42.script"
0_47823.path = "scene_3c_42.resources"
1_15055.path = "scene_3c_42.messages"

0_15056.path = "scene_3c_43.script"
0_47824.path = "scene_3c_43.resources"
1_15056.path = "scene_3c_43.messages"

0_15057.path = "scene_3c_44.script"
0_47825.path = "scene_3c_44.resources"
1_15057.path = "scene_3c_44.messages"

0_15058.path = "scene_3c_45.script"
0_47826.path = "scene_3c_45.resources"
1_15058.path = "scene_3c_45.messages"


[906.180]
path = "C3c_ST_180"

0_15059.path = "scene_3c_46.script"
0_47827.path = "scene_3c_46.resources"
1_15059.path = "scene_3c_46.messages"

0_15060.path = "scene_3c_47.script"
0_47828.path = "scene_3c_47.resources"
1_15060.path = "scene_3c_47.messages"

0_15061.path = "scene_3c_48.script"
0_47829.path = "scene_3c_48.resources"
1_15061.path = "scene_3c_48.messages"

0_15062.path = "scene_3c_49.script"
0_47830.path = "scene_3c_49.resources"
1_15062.path = "scene_3c_49.messages"

0_15063.path = "scene_3c_50.script"
0_47831.path = "scene_3c_50.resources"
1_15063.path = "scene_3c_50.messages"


[906.185]
path = "C3c_ST_185"

0_15064.path = "scene_3c_51.script"
0_47832.path = "scene_3c_51.resources"
1_15064.path = "scene_3c_51.messages"

0_15065.path = "scene_3c_52.script"
0_47833.path = "scene_3c_52.resources"
1_15065.path = "scene_3c_52.messages"

0_15066.path = "scene_3c_53.script"
0_47834.path = "scene_3c_53.resources"
1_15066.path = "scene_3c_53.messages"

0_15067.path = "scene_3c_54.script"
0_47835.path = "scene_3c_54.resources"
1_15067.path = "scene_3c_54.messages"

0_15068.path = "scene_3c_55.script"
0_47836.path = "scene_3c_55.resources"
1_15068.path = "scene_3c_55.messages"


[906.190]
path = "C3c_ST_190"

0_15069.path = "scene_3c_56.script"
0_47837.path = "scene_3c_56.resources"
1_15069.path = "scene_3c_56.messages"


[906.200]
path = "C3c_ST_200"

0_15074.path = "scene_3c_57.script"
0_47842.path = "scene_3c_57.resources"


[906.210]
path = "C3c_ST_210"

0_15075.path = "scene_3c_58.script"
0_47843.path = "scene_3c_58.resources"
1_15075.path = "scene_3c_58.messages"


[906.220]
path = "C3c_ST_220"

0_15076.path = "scene_3c_59.script"
0_47844.path = "scene_3c_59.resources"
1_15076.path = "scene_3c_59.messages"

0_15077.path = "scene_3c_60.script"
0_47845.path = "scene_3c_60.resources"
1_15077.path = "scene_3c_60.messages"

0_15078.path = "scene_3c_61.script"
0_47846.path = "scene_3c_61.resources"
1_15078.path = "scene_3c_61.messages"


[906.230]
path = "C3c_ST_230"

0_15079.path = "scene_3c_62.script"
0_47847.path = "scene_3c_62.resources"
1_15079.path = "scene_3c_62.messages"

0_15080.path = "scene_3c_63.script"
0_47848.path = "scene_3c_63.resources"
1_15080.path = "scene_3c_63.messages"

0_15081.path = "scene_3c_64.script"
0_47849.path = "scene_3c_64.resources"
1_15081.path = "scene_3c_64.messages"


[906.240]
path = "C3c_ST_240"

0_15082.path = "scene_3c_65.script"
0_47850.path = "scene_3c_65.resources"
1_15082.path = "scene_3c_65.messages"

0_15083.path = "scene_3c_160.script"
0_47851.path = "scene_3c_160.resources"

0_15085.path = "scene_3c_66.script"
0_47853.path = "scene_3c_66.resources"
1_15085.path = "scene_3c_66.messages"

0_15087.path = "scene_3c_161.script"
0_47855.path = "scene_3c_161.resources"

0_15089.path = "scene_3c_67.script"
0_47857.path = "scene_3c_67.resources"
1_15089.path = "scene_3c_67.messages"

0_15091.path = "scene_3c_162.script"
0_47859.path = "scene_3c_162.resources"

0_15093.path = "scene_3c_68.script"
0_47861.path = "scene_3c_68.resources"
1_15093.path = "scene_3c_68.messages"

0_15095.path = "scene_3c_163.script"
0_47863.path = "scene_3c_163.resources"

0_15097.path = "scene_3c_69.script"
0_47865.path = "scene_3c_69.resources"
1_15097.path = "scene_3c_69.messages"

0_15098.path = "scene_3c_70.script"
0_47866.path = "scene_3c_70.resources"
1_15098.path = "scene_3c_70.messages"


[906.250]
path = "C3c_ST_250"

0_15099.path = "scene_3c_71.script"
0_47867.path = "scene_3c_71.resources"


[906.260]
path = "C3c_ST_260"

0_15100.path = "scene_3c_72.script"
0_47868.path = "scene_3c_72.resources"


[906.270]
path = "C3c_ST_270"

0_15101.path = "scene_3c_73.script"
0_47869.path = "scene_3c_73.resources"
1_15101.path = "scene_3c_73.messages"


[906.280]
path = "C3c_ST_280"

0_15103.path = "scene_3c_74.script"
0_47871.path = "scene_3c_74.resources"
1_15103.path = "scene_3c_74.messages"


[906.290]
path = "C3c_ST_290"

0_15104.path = "scene_3c_75.script"
0_47872.path = "scene_3c_75.resources"


[906.300]
path = "C3c_ST_300"

0_15105.path = "scene_3c_76.script"
0_47873.path = "scene_3c_76.resources"
1_15105.path = "scene_3c_76.messages"

0_15106.path = "scene_3c_77.script"
0_47874.path = "scene_3c_77.resources"
1_15106.path = "scene_3c_77.messages"

0_15107.path = "scene_3c_78.script"
0_47875.path = "scene_3c_78.resources"
1_15107.path = "scene_3c_78.messages"

0_15108.path = "scene_3c_79.script"
0_47876.path = "scene_3c_79.resources"
1_15108.path = "scene_3c_79.messages"


[906.310]
path = "C3c_ST_310"

0_15109.path = "scene_3c_80.script"
0_47877.path = "scene_3c_80.resources"
1_15109.path = "scene_3c_80.messages"

0_15110.path = "scene_3c_81.script"
0_47878.path = "scene_3c_81.resources"
1_15110.path = "scene_3c_81.messages"

0_15111.path = "scene_3c_82.script"
0_47879.path = "scene_3c_82.resources"
1_15111.path = "scene_3c_82.messages"

0_15112.path = "scene_3c_150.script"
0_47880.path = "scene_3c_150.resources"
1_15112.path = "scene_3c_150.messages"

0_15113.path = "scene_3c_83.script"
0_47881.path = "scene_3c_83.resources"
1_15113.path = "scene_3c_83.messages"


[906.320]
path = "C3c_ST_320"

0_15114.path = "scene_3c_84.script"
0_47882.path = "scene_3c_84.resources"
1_15114.path = "scene_3c_84.messages"

0_15120.path = "scene_3c_85.script"
0_47888.path = "scene_3c_85.resources"
1_15120.path = "scene_3c_85.messages"


[906.330]
path = "C3c_ST_330"

0_15126.path = "scene_3c_86.script"
0_47894.path = "scene_3c_86.resources"
1_15126.path = "scene_3c_86.messages"

0_15127.path = "scene_3c_87.script"
0_47895.path = "scene_3c_87.resources"
1_15127.path = "scene_3c_87.messages"


[906.340]
path = "C3c_ST_340"

0_15128.path = "scene_3c_88.script"
0_47896.path = "scene_3c_88.resources"
1_15128.path = "scene_3c_88.messages"


[906.350]
path = "C3c_ST_350"

0_15132.path = "scene_3c_89.script"
0_47900.path = "scene_3c_89.resources"
1_15132.path = "scene_3c_89.messages"

0_15134.path = "scene_3c_90.script"
0_47902.path = "scene_3c_90.resources"
1_15134.path = "scene_3c_90.messages"

0_15137.path = "scene_3c_91.script"
0_47905.path = "scene_3c_91.resources"
1_15137.path = "scene_3c_91.messages"

0_15138.path = "scene_3c_92.script"
0_47906.path = "scene_3c_92.resources"
1_15138.path = "scene_3c_92.messages"

0_15139.path = "scene_3c_93.script"
0_47907.path = "scene_3c_93.resources"
1_15139.path = "scene_3c_93.messages"

0_15140.path = "scene_3c_94.script"
0_47908.path = "scene_3c_94.resources"
1_15140.path = "scene_3c_94.messages"

0_15141.path = "scene_3c_95.script"
0_47909.path = "scene_3c_95.resources"
1_15141.path = "scene_3c_95.messages"

0_15142.path = "scene_3c_96.script"
0_47910.path = "scene_3c_96.resources"
1_15142.path = "scene_3c_96.messages"

0_15143.path = "scene_3c_97.script"
0_47911.path = "scene_3c_97.resources"
1_15143.path = "scene_3c_97.messages"

0_15144.path = "scene_3c_98.script"
0_47912.path = "scene_3c_98.resources"
1_15144.path = "scene_3c_98.messages"


[906.360]
path = "C3c_ST_360"

0_15145.path = "scene_3c_99.script"
0_47913.path = "scene_3c_99.resources"
1_15145.path = "scene_3c_99.messages"

0_15146.path = "scene_3c_100.script"
0_47914.path = "scene_3c_100.resources"
1_15146.path = "scene_3c_100.messages"

0_15161.path = "scene_3c_101.script"
0_47929.path = "scene_3c_101.resources"
1_15161.path = "scene_3c_101.messages"


[906.370]
path = "C3c_ST_370"


[906.380]
path = "C3c_ST_380"

0_15176.path = "scene_3c_103.script"
0_47944.path = "scene_3c_103.resources"
1_15176.path = "scene_3c_103.messages"

0_15177.path = "scene_3c_104.script"
0_47945.path = "scene_3c_104.resources"
1_15177.path = "scene_3c_104.messages"

0_15178.path = "scene_3c_105.script"
0_47946.path = "scene_3c_105.resources"
1_15178.path = "scene_3c_105.messages"

0_15179.path = "scene_3c_106.script"
0_47947.path = "scene_3c_106.resources"
1_15179.path = "scene_3c_106.messages"


[906.390]
path = "C3c_ST_390"

0_15180.path = "scene_3c_107.script"
0_47948.path = "scene_3c_107.resources"
1_15180.path = "scene_3c_107.messages"

0_15181.path = "scene_3c_108.script"
0_47949.path = "scene_3c_108.resources"
1_15181.path = "scene_3c_108.messages"

0_15182.path = "scene_3c_109.script"
0_47950.path = "scene_3c_109.resources"
1_15182.path = "scene_3c_109.messages"

0_15183.path = "scene_3c_110.script"
0_47951.path = "scene_3c_110.resources"
1_15183.path = "scene_3c_110.messages"


[906.400]
path = "C3c_ST_400"

0_15184.path = "scene_3c_111.script"
0_47952.path = "scene_3c_111.resources"
1_15184.path = "scene_3c_111.messages"


[906.410]
path = "C3c_ST_410"

0_15185.path = "scene_3c_112.script"
0_47953.path = "scene_3c_112.resources"
1_15185.path = "scene_3c_112.messages"

0_15186.path = "scene_3c_113.script"
0_47954.path = "scene_3c_113.resources"
1_15186.path = "scene_3c_113.messages"

0_15187.path = "scene_3c_114.script"
0_47955.path = "scene_3c_114.resources"
1_15187.path = "scene_3c_114.messages"

0_15188.path = "scene_3c_115.script"
0_47956.path = "scene_3c_115.resources"
1_15188.path = "scene_3c_115.messages"

0_15189.path = "scene_3c_116.script"
0_47957.path = "scene_3c_116.resources"
1_15189.path = "scene_3c_116.messages"

0_15190.path = "scene_3c_117.script"
0_47958.path = "scene_3c_117.resources"
1_15190.path = "scene_3c_117.messages"

0_15191.path = "scene_3c_118.script"
0_47959.path = "scene_3c_118.resources"
1_15191.path = "scene_3c_118.messages"

0_15192.path = "scene_3c_119.script"
0_47960.path = "scene_3c_119.resources"
1_15192.path = "scene_3c_119.messages"

0_15193.path = "scene_3c_120.script"
0_47961.path = "scene_3c_120.resources"
1_15193.path = "scene_3c_120.messages"

0_15194.path = "scene_3c_121.script"
0_47962.path = "scene_3c_121.resources"
1_15194.path = "scene_3c_121.messages"

0_15195.path = "scene_3c_122.script"
0_47963.path = "scene_3c_122.resources"
1_15195.path = "scene_3c_122.messages"

0_15196.path = "scene_3c_123.script"
0_47964.path = "scene_3c_123.resources"
1_15196.path = "scene_3c_123.messages"

0_15197.path = "scene_3c_124.script"
0_47965.path = "scene_3c_124.resources"
1_15197.path = "scene_3c_124.messages"

0_15198.path = "scene_3c_126.script"
0_47966.path = "scene_3c_126.resources"
1_15198.path = "scene_3c_126.messages"

0_15199.path = "scene_3c_125.script"
0_47967.path = "scene_3c_125.resources"
1_15199.path = "scene_3c_125.messages"

0_15200.path = "scene_3c_127.script"
0_47968.path = "scene_3c_127.resources"
1_15200.path = "scene_3c_127.messages"


[906.420]
path = "C3c_ST_420"

0_15201.path = "scene_3c_128.script"
0_47969.path = "scene_3c_128.resources"


[906.430]
path = "C3c_ST_430"

0_15202.path = "scene_3c_129.script"
0_47970.path = "scene_3c_129.resources"


[906.440]
path = "C3c_ST_440"

0_15203.path = "scene_3c_130.script"
0_47971.path = "scene_3c_130.resources"


[906.450]
path = "C3c_ST_450"

0_15204.path = "scene_3c_131.script"
0_47972.path = "scene_3c_131.resources"
1_15204.path = "scene_3c_131.messages"


[906.460]
path = "C3c_ST_460"

0_15210.path = "scene_3c_135.script"
0_47978.path = "scene_3c_135.resources"
1_15210.path = "scene_3c_135.messages"

0_15212.path = "scene_3c_136.script"
0_47980.path = "scene_3c_136.resources"
1_15212.path = "scene_3c_136.messages"

0_15213.path = "scene_3c_137.script"
0_47981.path = "scene_3c_137.resources"
1_15213.path = "scene_3c_137.messages"

0_15214.path = "scene_3c_138.script"
0_47982.path = "scene_3c_138.resources"
1_15214.path = "scene_3c_138.messages"

0_15215.path = "scene_3c_139.script"
0_47983.path = "scene_3c_139.resources"
1_15215.path = "scene_3c_139.messages"

0_15216.path = "scene_3c_140.script"
0_47984.path = "scene_3c_140.resources"
1_15216.path = "scene_3c_140.messages"

0_15217.path = "scene_3c_142.script"
0_47985.path = "scene_3c_142.resources"
1_15217.path = "scene_3c_142.messages"

0_15220.path = "scene_3c_143.script"
0_47988.path = "scene_3c_143.resources"
1_15220.path = "scene_3c_143.messages"

0_15221.path = "scene_3c_144.script"
0_47989.path = "scene_3c_144.resources"
1_15221.path = "scene_3c_144.messages"


[906.470]
path = "C3c_ST_470"

0_15222.path = "scene_3c_145.script"
0_47990.path = "scene_3c_145.resources"
1_15222.path = "scene_3c_145.messages"

0_15223.path = "scene_3c_146.script"
0_47991.path = "scene_3c_146.resources"
1_15223.path = "scene_3c_146.messages"

0_15230.path = "scene_3c_147.script"
0_47998.path = "scene_3c_147.resources"
1_15230.path = "scene_3c_147.messages"


[906.480]
path = "C3c_ST_480"


[906.481]
path = "C3c_ST_481"


[906.482]
path = "C3c_ST_482"


[906.483]
path = "C3c_ST_483"


[906.484]
path = "C3c_ST_484"


[906.485]
path = "C3c_ST_485"


[906.486]
path = "C3c_ST_486"


[906.487]
path = "C3c_ST_487"


[906.488]
path = "C3c_ST_488"


[906.489]
path = "C3c_ST_489"


[906.490]
path = "C3c_ST_490"


[906.491]
path = "C3c_ST_491"
