name = "equipment"

columns = [
  { name = "u00",                      type = "undefined8",              width = 0 },
  { name = "u01",                      type = "undefined8",              width = 0 },
  { name = "u02",                      type = "uint8",                   width = 2 }, # skills.xlc[value] and 41.xlc[index]
  { name = "u03",                      type = "uint8",                   width = 0 },
  { name = "u04",                      type = "uint8",                   width = 0 },
  { name = "u05",                      type = "uint8",                   width = 0 },
  { name = "u06",                      type = "uint8",                   width = 0 },
  { name = "u07",                      type = "uint8",                   width = 2 },
  { name = "u08",                      type = "uint8",                   width = 0 },
  { name = "u09",                      type = "uint8",                   width = 0 },
  { name = "u0A",                      type = "uint8",                   width = 2 },
  { name = "u0B",                      type = "undefined8",              width = 0 },
  { name = "u0C",                      type = "undefined8",              width = 0 },
  { name = "u0D",                      type = "uint8",                   width = 0 },
  { name = "u0E",                      type = "uint8",                   width = 0 },
  { name = "u0F",                      type = "uint8",                   width = 0 },
  { name = "u10",                      type = "uint8",                   width = 0 },
  { name = "u11",                      type = "uint8",                   width = 0 },
  { name = "u12",                      type = "uint8",                   width = 2 },
  { name = "u13",                      type = "uint8",                   width = 2 },
  { name = "u14",                      type = "uint8",                   width = 2 },
  { name = "u15",                      type = "uint8",                   width = 2 },
  { name = "u16",                      type = "uint8",                   width = 0 },
  { name = "u17",                      type = "uint8",                   width = 2 },
  { name = "u18",                      type = "uint8",                   width = 2 },
  { name = "u19",                      type = "uint8",                   width = 3 },
  { name = "u1A",                      type = "uint8",                   width = 2 },
  { name = "u1B",                      type = "uint8",                   width = 3 },
  { name = "u1C",                      type = "uint8",                   width = 2 },
  { name = "u1D",                      type = "uint8",                   width = 3 },
  { name = "u1E",                      type = "uint8",                   width = 3 },
  { name = "u1F",                      type = "uint8",                   width = 3 },
  { name = "u20",                      type = "uint8",                   width = 3 },
  { name = "u21",                      type = "uint8",                   width = 3 },
  { name = "u22",                      type = "uint8",                   width = 3 },
  { name = "u23",                      type = "uint8",                   width = 3 },
  { name = "u24",                      type = "uint8",                   width = 3 },
  { name = "u25",                      type = "uint8",                   width = 3 },
  { name = "u26",                      type = "uint8",                   width = 3 },
  { name = "u27",                      type = "uint8",                   width = 0 },
  { name = "u28",                      type = "uint8",                   width = 2 },
  { name = "u29",                      type = "uint8",                   width = 2 },
  { name = "u2A",                      type = "uint8",                   width = 2 },
  { name = "u2B",                      type = "uint8",                   width = 2 },
  { name = "u2C",                      type = "uint8",                   width = 0 },
  { name = "u2D",                      type = "uint8",                   width = 0 },
  { name = "u2E",                      type = "undefined8",              width = 0 },
  { name = "u2F",                      type = "uint8",                   width = 2 },
  { name = "u30",                      type = "uint8",                   width = 0 },
  { name = "u31",                      type = "uint8",                   width = 0 },
  { name = "u32",                      type = "uint8",                   width = 0 },
  { name = "u33",                      type = "uint8",                   width = 0 },
  { name = "u34",                      type = "uint8",                   width = 0 },
  { name = "u35",                      type = "uint8",                   width = 0 },
  { name = "u36",                      type = "uint8",                   width = 0 },
  { name = "u37",                      type = "uint8",                   width = 0 },
  { name = "u38",                      type = "uint8",                   width = 0 },
  { name = "u39",                      type = "uint8",                   width = 0 },
  { name = "u3A",                      type = "uint8",                   width = 2 },
  { name = "u3B",                      type = "uint8",                   width = 2 },
  { name = "u3C",                      type = "uint8",                   width = 2 },
  { name = "u3D",                      type = "uint8",                   width = 2 },
  { name = "u3E",                      type = "uint8",                   width = 2 },
  { name = "u3F",                      type = "uint8",                   width = 2 },
  { name = "u40",                      type = "uint8",                   width = 2 },
  { name = "u41",                      type = "uint8",                   width = 2 },
  { name = "u42",                      type = "uint8",                   width = 2 },
  { name = "u43",                      type = "undefined8",              width = 0 },
  { name = "u44",                      type = "uint16",                  width = 3 },
  { name = "u46",                      type = "uint8",                   width = 0 },
  { name = "u47",                      type = "uint8",                   width = 0 }, # skills.xlc[value]
  { name = "u48",                      type = "undefined8",              width = 0 },
  { name = "u49",                      type = "undefined8",              width = 0 },
  { name = "u4A",                      type = "undefined8",              width = 0 },
  { name = "u4B",                      type = "undefined8",              width = 0 },
  { name = "u4C",                      type = "uint16",                  width = 2 },
  { name = "u4E",                      type = "uint8",                   width = 2 },
  { name = "u4F",                      type = "undefined8",              width = 0 },
  { name = "u50",                      type = "uint8",                   width = 0 },
  { name = "u51",                      type = "uint8",                   width = 0 },
  { name = "u52",                      type = "undefined8",              width = 0 },
  { name = "u53",                      type = "undefined8",              width = 0 },
  { name = "u54",                      type = "undefined8",              width = 0 },
  { name = "u55",                      type = "undefined8",              width = 0 },
  { name = "u56",                      type = "undefined8",              width = 0 },
  { name = "u57",                      type = "undefined8",              width = 0 },
  { name = "class_set_mask",           type = "uint64",                  width = 44, base = "bin" },
  { name = "u60",                      type = "uint8",                   width = 2 },
  { name = "u61",                      type = "uint8",                   width = 0 },
  { name = "u62",                      type = "uint16",                  width = 3 }, # battle_text.xlc[value]
  { name = "price",                    type = "uint16",                  width = 5 },
  { name = "u66",                      type = "uint8",                   width = 2 }, # 12.xlc[value]
  { name = "u67",                      type = "uint8",                   width = 2 }, # 42.xlc[value]
  { name = "u68",                      type = "uint8",                   width = 2 },
  { name = "u69",                      type = "uint8",                   width = 2 },
  { name = "u6A",                      type = "uint16",                  width = 3 },
  { name = "u6C",                      type = "uint16",                  width = 3 },
  { name = "u6E",                      type = "uint16",                  width = 3 },
  { name = "u70",                      type = "uint16",                  width = 3 },
  { name = "u72",                      type = "uint8",                   width = 0 },
  { name = "u73",                      type = "uint8",                   width = 0 },
  { name = "u74",                      type = "uint8",                   width = 0 },
  { name = "u75",                      type = "undefined8",              width = 0 },
  { name = "u76",                      type = "uint8",                   width = 2 },
  { name = "u77",                      type = "uint8",                   width = 0 },
  { name = "u78",                      type = "uint16",                  width = 4 },
  { name = "u7A",                      type = "uint16",                  width = 4, array_count = 4 },
  { name = "u82",                      type = "undefined8",              width = 3 },
  { name = "u83",                      type = "undefined8",              width = 0 },
  { name = "u84",                      type = "uint8",                   width = 0 },
  { name = "u85",                      type = "undefined8",              width = 0 },
  { name = "u86",                      type = "uint16",                  width = 3 },
  { name = "u88",                      type = "uint16",                  width = 3 }, # skills.xlc[value]
  { name = "u8A",                      type = "uint8",                   width = 2 },
  { name = "u8B",                      type = "uint8",                   width = 0 },
  { name = "u8C",                      type = "uint16",                  width = 3 },
  { name = "u8E",                      type = "uint8",                   width = 2 },
  { name = "u8F",                      type = "undefined8",              width = 0 },
  { name = "u90",                      type = "uint16",                  width = 3 },
  { name = "u92",                      type = "uint8",                   width = 2 },
  { name = "u93",                      type = "uint8",                   width = 2 },
  { name = "u94",                      type = "undefined8",              width = 0 }, # maybe padding
  { name = "u95",                      type = "undefined8",              width = 0 }, # maybe padding
  { name = "u96",                      type = "undefined8",              width = 0 }, # maybe padding
  { name = "u97",                      type = "undefined8",              width = 0 }  # maybe padding
]
