name = "equipment"

columns = [
  { name = "u00",                      type = "undefined8",              width = 0 },
  { name = "u01",                      type = "undefined8",              width = 0 },
  { name = "u02",                      type = "uint8",                   width = 2 }, # skills.xlc[value] and 41.xlc[index]
  { name = "u03",                      type = "uint8",                   width = 0 },
  { name = "u04",                      type = "uint8",                   width = 0 },
  { name = "u05",                      type = "uint8",                   width = 0 },
  { name = "u06",                      type = "uint8",                   width = 0 },
  { name = "u07",                      type = "uint8",                   width = 2 },
  { name = "u08",                      type = "uint8",                   width = 0 },
  { name = "u09",                      type = "uint8",                   width = 0 },
  { name = "u0A",                      type = "uint8",                   width = 2 },
  { name = "u0B",                      type = "undefined8",              width = 0 },
  { name = "u0C",                      type = "undefined8",              width = 0 },
  { name = "u0D",                      type = "uint8",                   width = 0 },
  { name = "u0E",                      type = "uint8",                   width = 0 },
  { name = "u0F",                      type = "uint8",                   width = 0 },
  { name = "u10",                      type = "uint8",                   width = 0 },
  { name = "u11",                      type = "uint8",                   width = 0 },
  { name = "u12",                      type = "uint8",                   width = 2 },
  { name = "on_hit", columns = [
    { name = "type",                   type = "uint8",                   width = 2, enum = [ ] },
    { name = "index",                  type = "uint8",                   width = 2 },
    { name = "chance",                 type = "uint8",                   width = 2 },
    { name = "value_type",             type = "uint8",                   width = 0 },
    { name = "value",                  type = "uint8",                   width = 2 }
  ] },
  { name = "rt",                       type = "uint8",                   width = 2 },
  { name = "atk",                      type = "uint8",                   width = 3 },
  { name = "def",                      type = "uint8",                   width = 2 },
  { name = "hp",                       type = "uint8",                   width = 3 },
  { name = "mp",                       type = "uint8",                   width = 2 },
  { name = "str",                      type = "uint8",                   width = 3 },
  { name = "vit",                      type = "uint8",                   width = 3 },
  { name = "dex",                      type = "uint8",                   width = 3 },
  { name = "agi",                      type = "uint8",                   width = 3 },
  { name = "avd",                      type = "uint8",                   width = 3 },
  { name = "int",                      type = "uint8",                   width = 3 },
  { name = "mnd",                      type = "uint8",                   width = 3 },
  { name = "res",                      type = "uint8",                   width = 3 },
  { name = "luk",                      type = "uint8",                   width = 3 },
  { name = "weight",                   type = "uint8",                   width = 3 },
  { name = "damage", columns = [
    { name = "type",                   type = "uint8",                   width = 10, enum = [ "None", "Crushing", "Slashing", "Piercing" ] },
    { name = "bonus",                  type = "uint8",                   width = 2 }
  ] },
  { name = "u29",                      type = "uint8",                   width = 2 },
  { name = "u2A",                      type = "uint8",                   width = 2 },
  { name = "u2B",                      type = "uint8",                   width = 2 },
  { name = "u2C",                      type = "uint8",                   width = 0 },
  { name = "u2D",                      type = "uint8",                   width = 0 },
  { name = "racial_affinity", columns = [
    { name = "type",                   type = "uint8",                   width = 9, enum = [ "None", "Human", "Beast", "Reptile", "Dragon", "Divine", "Umbra", "Faerie", "Phantom", "Golem" ] },
    { name = "bonus",                  type = "uint8",                   width = 2 }
  ] },
  { name = "u30",                      type = "uint8",                   width = 0 },
  { name = "u31",                      type = "uint8",                   width = 0 },
  { name = "u32",                      type = "uint8",                   width = 0 },
  { name = "u33",                      type = "uint8",                   width = 0 },
  { name = "u34",                      type = "uint8",                   width = 0 },
  { name = "u35",                      type = "uint8",                   width = 0 },
  { name = "u36",                      type = "uint8",                   width = 0 },
  { name = "u37",                      type = "uint8",                   width = 0 },
  { name = "u38",                      type = "uint8",                   width = 0 },
  { name = "elemental_affinity", columns = [
    { name = "type",                   type = "uint8",                   width = 11, enum = [ "None", "Air", "Earth", "Lightning", "Water", "Fire", "Ice", "Light", "Dark" ] },
    { name = "bonus",                  type = "uint8",                   width = 2 }
  ] },
  { name = "u3B",                      type = "uint8",                   width = 2 },
  { name = "u3C",                      type = "uint8",                   width = 2 },
  { name = "u3D",                      type = "uint8",                   width = 2 },
  { name = "u3E",                      type = "uint8",                   width = 2 },
  { name = "u3F",                      type = "uint8",                   width = 2 },
  { name = "u40",                      type = "uint8",                   width = 2 },
  { name = "u41",                      type = "uint8",                   width = 2 },
  { name = "u42",                      type = "uint8",                   width = 2 },
  { name = "u43",                      type = "undefined8",              width = 0 },
  { name = "effect", columns = [
    { name = "index",                  type = "uint16",                  width = 3 },
    { name = "charges",                type = "uint8",                   width = 0 }
  ] },
  { name = "u47",                      type = "uint8",                   width = 0 }, # skills.xlc[value]
  { name = "u48",                      type = "undefined8",              width = 0 },
  { name = "u49",                      type = "undefined8",              width = 0 },
  { name = "u4A",                      type = "undefined8",              width = 0 },
  { name = "u4B",                      type = "undefined8",              width = 0 },
  { name = "skill_bonus", columns = [
    { name = "index",                  type = "uint16",                  width = 2 },
    { name = "levels",                 type = "uint8",                   width = 2 }
  },
  { name = "u4F",                      type = "undefined8",              width = 0 },
  { name = "u50",                      type = "uint8",                   width = 0 },
  { name = "u51",                      type = "uint8",                   width = 0 },
  { name = "u52",                      type = "undefined8",              width = 0 },
  { name = "u53",                      type = "undefined8",              width = 0 },
  { name = "u54",                      type = "undefined8",              width = 0 },
  { name = "u55",                      type = "undefined8",              width = 0 },
  { name = "u56",                      type = "undefined8",              width = 0 },
  { name = "u57",                      type = "undefined8",              width = 0 },
  { name = "class_set_mask",           type = "uint64",                  width = 44, base = "bin" },
  { name = "level",                    type = "uint8",                   width = 2 }, # unused?
  { name = "u61",                      type = "uint8",                   width = 0 },
  { name = "description_index",        type = "uint16",                  width = 3 }, # battle_text.xlc[value]
  { name = "price",                    type = "uint16",                  width = 5 },
  { name = "u66",                      type = "uint8",                   width = 2 }, # 12.xlc[value]
  { name = "u67",                      type = "uint8",                   width = 2 }, # 42.xlc[value]
  { name = "u68",                      type = "uint8",                   width = 2 },
  { name = "u69",                      type = "uint8",                   width = 2 },
  { name = "u6A",                      type = "uint16",                  width = 3 },
  { name = "u6C",                      type = "uint16",                  width = 3 },
  { name = "u6E",                      type = "uint16",                  width = 3 },
  { name = "u70",                      type = "uint16",                  width = 3 },
  { name = "u72",                      type = "uint8",                   width = 0 },
  { name = "u73",                      type = "uint8",                   width = 0 },
  { name = "u74",                      type = "uint8",                   width = 0 }, # icon background / rarity?
  { name = "u75",                      type = "undefined8",              width = 0 },
  { name = "u76",                      type = "uint8",                   width = 2 },
  { name = "u77",                      type = "uint8",                   width = 0 },
  { name = "u78",                      type = "uint16",                  width = 4 },
  { name = "u7A",                      type = "uint16",                  width = 4, array_count = 4 },
  { name = "u82",                      type = "undefined8",              width = 3 },
  { name = "u83",                      type = "undefined8",              width = 0 },
  { name = "u84",                      type = "uint8",                   width = 0 },
  { name = "u85",                      type = "undefined8",              width = 0 },
  { name = "name_index",               type = "uint16",                  width = 3 }, # battle_text.xlc[value]
  { name = "battle_ability",           type = "uint16",                  width = 3 }, # skills.xlc[value]
  { name = "u8A",                      type = "uint8",                   width = 2 },
  { name = "u8B",                      type = "uint8",                   width = 0 },
  { name = "u8C",                      type = "uint16",                  width = 3 },
  { name = "u8E",                      type = "uint8",                   width = 2 },
  { name = "u8F",                      type = "undefined8",              width = 0 },
  { name = "u90",                      type = "uint16",                  width = 3 },
  { name = "u92",                      type = "uint8",                   width = 2 },
  { name = "u93",                      type = "uint8",                   width = 2 },
  { name = "u94",                      type = "undefined8",              width = 0 }, # maybe padding
  { name = "u95",                      type = "undefined8",              width = 0 }, # maybe padding
  { name = "u96",                      type = "undefined8",              width = 0 }, # maybe padding
  { name = "u97",                      type = "undefined8",              width = 0 }  # maybe padding
]
