name = "tarot_card_data"

columns = [
  { name = "u00",           type = "uint8",  width = 2                  },
  { name = "u01",           type = "uint8",  width = 2                  },
  { name = "item_id",       type = "uint16"                             }, # appears to be unsupported/ignored in Reborn
  { name = "u04",           type = "uint16", width = 2                  }, # effect id
  { name = "u06",           type = "uint8",  width = 3                  }, # effect id
  { name = "u07",           type = "uint8",  width = 3                  }, # effect id
  { name = "u08",           type = "uint8",  width = 3                  }, # effect id
  { name = "stats", columns = [
    { name = "HP",          type = "uint8",             array_count = 3 },
    { name = "MP",          type = "uint8",             array_count = 3 },
    { name = "STR",         type = "uint8",             array_count = 3 },
    { name = "VIT",         type = "uint8",             array_count = 3 },
    { name = "DEX",         type = "uint8",             array_count = 3 },
    { name = "AGI",         type = "uint8",             array_count = 3 },
    { name = "AVD",         type = "uint8",             array_count = 3 },
    { name = "INT",         type = "uint8",             array_count = 3 },
    { name = "MND",         type = "uint8",             array_count = 3 },
    { name = "RES",         type = "uint8",             array_count = 3 },
  ] },
  { name = "elements", columns = [
    { name = "vyce",        type = "uint8",             array_count = 3 },
    { name = "catiua",      type = "uint8",             array_count = 3 },
    { name = "donnalto",    type = "uint8",             array_count = 3 },
    { name = "sara",        type = "uint8",             array_count = 3 },
    { name = "voltare",     type = "uint8",             array_count = 3 },
    { name = "felicia",     type = "uint8",             array_count = 3 },
  ] },
  { name = "__padding",     type = "uint8"                              },
]
